<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MacBook-Pro-de-M.local" name="dataaccess.ConnectorTest" tests="1" failures="1" timestamp="26 Apr 2021 22:56:15 GMT" time="1.3" errors="0">
  <testcase name="testDataBaseConnection on testDataBaseConnection(dataaccess.ConnectorTest)" time="0.124" classname="dataaccess.ConnectorTest">
    <failure type="java.lang.AssertionError" message="No conexion exitosa">
      <![CDATA[java.lang.AssertionError: No conexion exitosa
	at org.junit.Assert.fail(Assert.java:88)
	at dataaccess.ConnectorTest.testDataBaseConnection(ConnectorTest.java:22)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testDataBaseConnection on testDataBaseConnection(dataaccess.ConnectorTest) -->
</testsuite> <!-- dataaccess.ConnectorTest -->
